### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by BonoVanderpoorten** [1modm/1modm.github.io#1]
Hey,
Sorry to bother you, I was looking at your .io generated with the files from this repo and I wonder what kind of framework you use to manage it?
I really like the way it looks and I've been wanting something like this for a while and didn't found a direct way to contact you so I made an issue. Sorry!

Kind Regards,

**Comment by 1modm** [comment]
Hey Bono!

I used jekyll, and the html theme https://github.com/heiswayi/heiswayi.github.io_jekyll_source

I have just checked that this specific theme is not available now, but you can find a lot of nice jekyll in github or http://jekyllthemes.org/

Thanks
Miguel
